name: Publish
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Publish Gradle Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          java-package: jdk
      - run: chmod +x gradlew
      - run: ./gradlew publishPlugins --info --stacktrace -Dgradle.publish.key=${GRADLE_PUBLISH_KEY} -Dgradle.publish.secret=${GRADLE_PUBLISH_SECRET}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
